// <auto-generated />
using System;
using GreenDriveApi324119278.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenDriveApi324119278.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503012056_CriarMigration")]
    partial class CriarMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("GreenDriveApi324119278.Model.Bateria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CapacidadeKWh")
                        .HasColumnType("REAL");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SaudeBateria")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Baterias");
                });

            modelBuilder.Entity("GreenDriveApi324119278.Model.EstacaoCarga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CargaDisponivelKW")
                        .HasColumnType("REAL");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoCarga")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstacoesCarga");
                });

            modelBuilder.Entity("GreenDriveApi324119278.Model.OrdemReciclagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CustoProcessamento")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EstacaoCargaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EstacaoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BateriaId");

                    b.HasIndex("EstacaoCargaId");

                    b.ToTable("OrdensReciclagem");
                });

            modelBuilder.Entity("GreenDriveApi324119278.Model.RegistroTelemetria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BateriaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperatura")
                        .HasColumnType("REAL");

                    b.Property<double>("Voltagem")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("BateriaId");

                    b.ToTable("RegistrosTelemetria");
                });

            modelBuilder.Entity("GreenDriveApi324119278.Model.OrdemReciclagem", b =>
                {
                    b.HasOne("GreenDriveApi324119278.Model.Bateria", "Bateria")
                        .WithMany()
                        .HasForeignKey("BateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenDriveApi324119278.Model.EstacaoCarga", "EstacaoCarga")
                        .WithMany()
                        .HasForeignKey("EstacaoCargaId");

                    b.Navigation("Bateria");

                    b.Navigation("EstacaoCarga");
                });

            modelBuilder.Entity("GreenDriveApi324119278.Model.RegistroTelemetria", b =>
                {
                    b.HasOne("GreenDriveApi324119278.Model.Bateria", "Bateria")
                        .WithMany()
                        .HasForeignKey("BateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bateria");
                });
#pragma warning restore 612, 618
        }
    }
}
